### ISSUE TITLE
Exception AttributeError: "'Service' object has no attribute 'process'"

### ISSUE THREAD

**Issue by dyno8426** [dhruvramani/Terminal-on-FB-Messenger#10]
Dhruv,

I am trying to use this script from Ubuntu 14.04. I have installed 'selenium' python package and Google Chrome as well on my PC. But on running this script, I am getting the following error:

```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    driver = webdriver.Chrome(chrome_options=chrome_options)
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 61, in __init__
    self.service.start()
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 69, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f874d2673d0>> ignored
```

Can you please help me resolve this error?
Thanks in advance.
P. S. I am running the script from a directory which is not the home directory.

**Comment by dhruvramani** [comment]
It needs an executable path as an argument. Follow up this [link](http://stackoverflow.com/a/8259152/4534903)

**Comment by dhruvramani** [comment]
This one might help too : https://stackoverflow.com/questions/22130109/cant-use-chrome-driver-for-selenium
